FROM gcr.io/action-containers/mvn:3.6.3-java8-4


RUN apt-get install -y software-properties-common \
    && apt-key adv \
        --keyserver keyserver.ubuntu.com \
        --recv-keys E298A3A825C0D65DFD57CBB651716619E084DAB9 \
    && add-apt-repository \
        'deb https://cloud.r-project.org/bin/linux/ubuntu bionic-cran40/' \
    && apt-get update \
    && apt-get install -y \
        python3 \
        r-base

