FROM armadik/livy:dev

USER root
RUN apt-get update && DEBIAN_FRONTEND=noninteractive apt-get install -y --no-install-recommends \
        python-dev \
        python3-pip && \
    rm -rf /var/lib/apt/lists/* \

ADD spark-entrypoint.sh /entrypoint.sh
RUN chmod a+x /entrypoint.sh

USER default
ENTRYPOINT ["/entrypoint.sh"]