{{- $name := include "livycluster.name" . -}}
{{- $chart := include "livycluster.chart" . -}}
{{- $releaseName := .Release.Name -}}
{{- $releaseService := .Release.Service -}}
{{- range .Values.storageClasses }}
---
apiVersion: storage.k8s.io/v1
kind: StorageClass
metadata:
  name: {{ .name }}
  namespace: {{ .Release.Namespace }}
  labels:
    app.kubernetes.io/name: {{ $name }}
    helm.sh/chart: {{ $chart }}
    app.kubernetes.io/instance: {{ $releaseName }}
    app.kubernetes.io/managed-by: {{ $releaseService }}
{{- if .default }}
  annotations:
    storageclass.kubernetes.io/is-default-class: "true"
{{- end }}
provisioner: {{ .provisioner }}
{{- if .parameters }}
parameters:
{{ toYaml .parameters | indent 2 }}
{{- end }}
{{- if .reclaimPolicy }}
reclaimPolicy: {{ .reclaimPolicy }}
{{- end }}
{{- if .volumeBindingMode }}
volumeBindingMode: {{ .volumeBindingMode }}
{{- end }}
{{- end }}
